import React, { useState } from 'react';
import { LocationProfile, OrganizationProfile } from '../../types';
import { X, Building2, MapPin, Phone, Mail, Clock, Globe, Shield, Sparkles } from 'lucide-react';

interface LocationProfileModalProps {
  isOpen: boolean;
  onClose: () => void;
  location?: LocationProfile;
  isNew?: boolean;
  organization: OrganizationProfile;
  onSave: (loc: LocationProfile) => void;
}

export const LocationProfileModal: React.FC<LocationProfileModalProps> = ({
  isOpen,
  onClose,
  location,
  isNew = false,
  organization,
  onSave
}) => {
  const [formData, setFormData] = useState<LocationProfile>(location || {
    id: `loc-new-${Date.now()}`,
    organizationId: organization.id,
    locationName: 'Kura Revolving Sushi Bar',
    displayName: 'Kura Sushi #108 - San Jose',
    storeNumber: '#108',
    locationCode: 'SJC-108',
    hierarchyPath: `${organization.legalName} > West Region > Northern California District > Kura Sushi #108`,
    addressLine1: '1600 Saratoga Ave',
    city: 'San Jose',
    state: 'CA',
    zipCode: '95129',
    country: 'United States',
    phone: '+1 (408) 555-0108',
    email: 'store108@kurasushi.com',
    timezone: 'America/Los_Angeles',
    generalManagerName: 'Alex Kim',
    generalManagerEmail: 'alex.kim@kurasushi.com',
    regionName: 'West Region',
    districtName: 'Northern California District',
    status: 'active',
    operatingHours: 'Mon-Sun: 11:00 AM - 10:00 PM',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  });

  if (!isOpen) return null;

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    onSave({
      ...formData,
      updatedAt: new Date().toISOString()
    });
  };

  const handleAutoGenerateDisplayName = () => {
    const brand = organization.displayName.replace(' USA', '').replace(' Global', '');
    setFormData({
      ...formData,
      displayName: `${brand} ${formData.storeNumber} - ${formData.city}`
    });
  };

  return (
    <div className="fixed inset-0 z-60 bg-slate-950/80 backdrop-blur-xs flex items-center justify-center p-4 animate-in fade-in">
      <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl max-w-2xl w-full p-6 shadow-2xl space-y-4 max-h-[90vh] overflow-y-auto">
        <div className="flex items-center justify-between border-b border-slate-100 dark:border-slate-800 pb-3">
          <div className="flex items-center gap-2">
            <Building2 className="w-5 h-5 text-indigo-600" />
            <h3 className="text-base font-bold text-slate-900 dark:text-white">
              {isNew ? 'Register New Operating Location / Unit' : 'Edit Location Profile & Brand Identity'}
            </h3>
          </div>
          <button onClick={onClose} className="p-1 text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 cursor-pointer">
            <X className="w-5 h-5" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="space-y-4 text-xs">
          {/* Identity Fields */}
          <div className="bg-slate-50 dark:bg-slate-800/50 p-4 rounded-xl space-y-3">
            <div className="flex items-center justify-between">
              <span className="font-bold text-slate-700 dark:text-slate-200 text-xs">Naming &amp; Store Identifiers</span>
              <button
                type="button"
                onClick={handleAutoGenerateDisplayName}
                className="text-[11px] text-indigo-600 dark:text-indigo-400 hover:underline flex items-center gap-1 cursor-pointer font-semibold"
              >
                <Sparkles className="w-3 h-3" /> Auto-Format Display Name
              </button>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
              <div>
                <label className="block text-slate-500 font-medium mb-1">Store Number / Unit #</label>
                <input
                  type="text"
                  required
                  placeholder="e.g. #104"
                  value={formData.storeNumber}
                  onChange={(e) => setFormData({ ...formData, storeNumber: e.target.value })}
                  className="w-full px-3 py-2 rounded-xl border border-slate-300 dark:border-slate-700 dark:bg-slate-800 font-bold"
                />
              </div>

              <div>
                <label className="block text-slate-500 font-medium mb-1">Location Code</label>
                <input
                  type="text"
                  required
                  placeholder="e.g. SF-104"
                  value={formData.locationCode}
                  onChange={(e) => setFormData({ ...formData, locationCode: e.target.value })}
                  className="w-full px-3 py-2 rounded-xl border border-slate-300 dark:border-slate-700 dark:bg-slate-800 font-mono"
                />
              </div>

              <div>
                <label className="block text-slate-500 font-medium mb-1">Operating Status</label>
                <select
                  value={formData.status}
                  onChange={(e) => setFormData({ ...formData, status: e.target.value as any })}
                  className="w-full px-3 py-2 rounded-xl border border-slate-300 dark:border-slate-700 dark:bg-slate-800 font-semibold"
                >
                  <option value="active">Active Operation</option>
                  <option value="opening_soon">Opening Soon</option>
                  <option value="remodeling">Remodeling / Renovation</option>
                  <option value="inactive">Inactive</option>
                </select>
              </div>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div>
                <label className="block text-slate-500 font-medium mb-1">Legal Location Title</label>
                <input
                  type="text"
                  required
                  value={formData.locationName}
                  onChange={(e) => setFormData({ ...formData, locationName: e.target.value })}
                  className="w-full px-3 py-2 rounded-xl border border-slate-300 dark:border-slate-700 dark:bg-slate-800 font-medium"
                />
              </div>

              <div>
                <label className="block text-slate-500 font-medium mb-1">Public Display Name</label>
                <input
                  type="text"
                  required
                  value={formData.displayName}
                  onChange={(e) => setFormData({ ...formData, displayName: e.target.value })}
                  className="w-full px-3 py-2 rounded-xl border border-slate-300 dark:border-slate-700 dark:bg-slate-800 font-bold"
                />
              </div>
            </div>
          </div>

          {/* Address & Contact */}
          <div className="bg-slate-50 dark:bg-slate-800/50 p-4 rounded-xl space-y-3">
            <span className="font-bold text-slate-700 dark:text-slate-200 text-xs">Physical Address &amp; Contact</span>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div className="sm:col-span-2">
                <label className="block text-slate-500 font-medium mb-1">Street Address</label>
                <input
                  type="text"
                  required
                  value={formData.addressLine1}
                  onChange={(e) => setFormData({ ...formData, addressLine1: e.target.value })}
                  className="w-full px-3 py-2 rounded-xl border border-slate-300 dark:border-slate-700 dark:bg-slate-800"
                />
              </div>

              <div>
                <label className="block text-slate-500 font-medium mb-1">City</label>
                <input
                  type="text"
                  required
                  value={formData.city}
                  onChange={(e) => setFormData({ ...formData, city: e.target.value })}
                  className="w-full px-3 py-2 rounded-xl border border-slate-300 dark:border-slate-700 dark:bg-slate-800"
                />
              </div>

              <div className="grid grid-cols-2 gap-2">
                <div>
                  <label className="block text-slate-500 font-medium mb-1">State</label>
                  <input
                    type="text"
                    required
                    value={formData.state}
                    onChange={(e) => setFormData({ ...formData, state: e.target.value })}
                    className="w-full px-3 py-2 rounded-xl border border-slate-300 dark:border-slate-700 dark:bg-slate-800 font-bold"
                  />
                </div>
                <div>
                  <label className="block text-slate-500 font-medium mb-1">ZIP Code</label>
                  <input
                    type="text"
                    required
                    value={formData.zipCode}
                    onChange={(e) => setFormData({ ...formData, zipCode: e.target.value })}
                    className="w-full px-3 py-2 rounded-xl border border-slate-300 dark:border-slate-700 dark:bg-slate-800"
                  />
                </div>
              </div>

              <div>
                <label className="block text-slate-500 font-medium mb-1">Branch Telephone</label>
                <input
                  type="tel"
                  required
                  value={formData.phone}
                  onChange={(e) => setFormData({ ...formData, phone: e.target.value })}
                  className="w-full px-3 py-2 rounded-xl border border-slate-300 dark:border-slate-700 dark:bg-slate-800"
                />
              </div>

              <div>
                <label className="block text-slate-500 font-medium mb-1">General Manager Name</label>
                <input
                  type="text"
                  required
                  value={formData.generalManagerName}
                  onChange={(e) => setFormData({ ...formData, generalManagerName: e.target.value })}
                  className="w-full px-3 py-2 rounded-xl border border-slate-300 dark:border-slate-700 dark:bg-slate-800"
                />
              </div>
            </div>
          </div>

          <div className="flex items-center justify-end gap-2 pt-2">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded-xl text-xs font-semibold cursor-pointer"
            >
              Cancel
            </button>
            <button
              type="submit"
              className="px-5 py-2 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl text-xs font-bold shadow-md cursor-pointer"
            >
              {isNew ? 'Create Location' : 'Save Location Identity'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};
